#!/bin/sh
PRESET_FILE="$XDG_CONFIG_HOME/kitty_runner/presets";
MESSAGE="Loading preset";
#Set MENU_COMMAND to something that can read from stdin
#for lines to select from. This gets set explicitly via cmd args
MENU_COMMAND=""
MODE="normal_mode"
ARGS=""

err(){
        echo "$1"; exit 1
}

strip_comments(){
        sed '/^\s*#.*$/d;' "$1"
}

prep(){
        sed 's/;\s*#.*$//' -
}

dmenu_mode(){
        DET=$(strip_comments "$PRESET_FILE" | $MENU_COMMAND | prep );
        echo "$MESSAGE $DET" "$@";
}

tofi_mode() {
        DET=$(strip_comments "$PRESET_FILE" | $MENU_COMMAND | prep )
}

wofi_mode() {
        DET=$(strip_comments "$PRESET_FILE" | $MENU_COMMAND | prep )
}

normal_mode(){
        DET=$( strip_comments "$PRESET_FILE" | fzf | prep );
}

if [ "$1" ]; then
while [ "$1" ]; do
        case "$1" in
                --dmenu-mode | -d )
                        MENU_COMMAND="dmenu" MODE="dmenu_mode"; shift;;
                --tofi-mode | -t )
                        MENU_COMMAND="tofi" MODE="tofi_mode"; shift;;
                --wofi-mode | -w )
                        MENU_COMMAND="wofi --dmenu" MODE="wofi_mode"; shift;;
                --normal-mode | -n )
                        MODE="normal_mode"; shift;;
                -p | --preset-file )
                        shift;
                        if [ ! -e "$1" ]; then
                                err "Presets file $1 does not exist"

                        else
                                PRESET_FILE="$1"
                                shift

                        fi
                        ;;

                * )
                        ARGS="$ARGS $1";
                        shift;;

        esac
done
fi

echo "Using Presets file: $PRESET_FILE"
$MODE
if [ -z "$DET" ]; then
        printf "Please select a preset";
else
        eval exec $DET $ARGS;
fi
