#!/bin/sh
PRESET_FILE="$XDG_CONFIG_HOME/kitty_runner/presets";
PRESET_BASE_DIR="$XDG_CONFIG_HOME/kitty_runner";
MESSAGE="Loading preset";
IS_END_OF_PROCESSED_ARGS=0;
IS_FORKING=0
#Set MENU_COMMAND to something that can read from stdin
#for lines to select from. This gets set explicitly via cmd args
MENU_COMMAND=""
MODE="normal_mode"
ARGS=""

err(){
        echo "$1"; exit 1
}

strip_comments(){
        sed '/^\s*#.*$/d;' "$1"
}

prep(){
        sed 's/;\s*#.*$//' -
}

dmenu_mode(){
        DET=$(strip_comments "$PRESET_FILE" | $MENU_COMMAND | prep );
        echo "$MESSAGE $DET" "$@";
}

tofi_mode() {
        DET=$(strip_comments "$PRESET_FILE" | $MENU_COMMAND | prep )
}

wofi_mode() {
        DET=$(strip_comments "$PRESET_FILE" | $MENU_COMMAND | prep )
}

normal_mode(){
        DET=$( strip_comments "$PRESET_FILE" | fzf | prep );
}


run() {

        echo "Running preset $DET $ARGS"
        if [ "$IS_FORKING" = 0 ]; then
                        eval exec $DET $ARGS;
        else
                        eval exec setsid -f $DET $ARGS;
        fi
}

if [ "$1" ]; then
while [ "$1" ]; do
        case "$1" in
                --dmenu-mode | -d )
                        MENU_COMMAND="dmenu" MODE="dmenu_mode"; shift;;
                --tofi-mode | -t )
                        MENU_COMMAND="tofi" MODE="tofi_mode"; shift;;
                --wofi-mode | -w )
                        MENU_COMMAND="wofi --dmenu" MODE="wofi_mode"; shift;;
                --normal-mode | -n )
                        MODE="normal_mode"; shift;;
                -p | --preset-file )
                        shift;
                        if [ ! -e "$1" ]; then
                                err "Presets file $1 does not exist"

                        else
                                PRESET_FILE="$1"
                                shift

                        fi
                        ;;
                -P | --preset )
                        shift;
                        if [ ! -e "$PRESET_BASE_DIR/$1" ]; then
                                err "Preset $1 not found in $PRESET_BASE_DIR"

                        else
                                PRESET_FILE="$PRESET_BASE_DIR/$1"
                                shift

                        fi
                        ;;

                -f | --fork )
                        shift;
                        IS_FORKING=1
                        ;;

                -- )
                        IS_END_OF_PROCESSED_ARGS=1;
                        shift;
                        ;;

                * )
                        if [ "$IS_END_OF_PROCESSED_ARGS" = 1 ]; then
                                ARGS="$ARGS $1";
                        fi

                        shift
                        ;;

        esac
done
fi

echo "Using Presets file: $PRESET_FILE"
$MODE
if [ -z "$DET" ]; then
        printf "Please select a preset";
else
        run
fi
